- datapacks/omega-flowey/data/_/functions/attack.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/reset_scores.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/tick.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/bullet/loop.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/indicator/initialize.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/indicator/loop.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/indicator/loop/face_player.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/indicator/loop/pause_eye.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/indicator/loop/summon_bullets.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/indicator/terminate.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/reset_scores.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/start.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/tick.mcfunction
- datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-upper/indicator/terminate.mcfunction
- datapacks/omega-flowey/data/entity/functions/utils/face_closest_player.mcfunction
- datapacks/omega-flowey/data/omega-flowey/functions/rng.mcfunction
- datapacks/omega-flowey/data/omega-flowey/functions/setup.mcfunction
to play the attack in-game, run:
```mcfunction
function _:reset
function _:attack
```
| in-game | undertale |
|-|-|
| https://youtu.be/8SJqWQZzsrY | https://youtu.be/2vh0Jx5-EmQ |
---
this PR also:
- contains a world sync
> add mvp for `x-bullets-lower` attack

- .github/workflows/datapack.yml
**fixes typo in https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/54**
Misode made a workflow that can run PackTest without any special third party code. Just some simple `curl`s in a shell script (the workflow file itself) and it runs much faster than before with `packtest_runner`.
- see: https://discord.com/channels/154777837382008833/1185733502294044802/1190466881488945162
interestingly it seems like caching is already implemented/not worth implementing in most of the download/install steps. After the actual server starting + running tests, all the other steps are 1s or 0s.
So it's either already caching (likely) or doesn't even need it if its not.
---
tests still run as expected. runtime goes from >2m to ~30s.
N/A
see workflow runs associated with this branch's …
> upgrade `PackTest` workflow to simpler + faster version

- .gitignore
- README.md
- package-scripts.js
- package-scripts/sync-world.js
- package.json
- yarn.lock
**closes #53**
This PR replaces the terminal command we use to backup the world (`yarn sync`) with a node script with the same behavior and new functionality to extract the world to a developer's local `.minecraft/saves` folder.
Terminology:
- **"sync up"**: compresses the local save to `./world.zip`
- **"sync down"**: extracts `./world.zip` to the local save
---
(https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/aeb07d1f99b07b657858bb65ae10e844518bc30b)
Tested by running the following steps:
1. sync-up world with `yarn sync`
2. move player to a different spot in the world (e.g. turn around 180 degrees)
3. sync-down world with `yarn down`
4. open world and see that player is in the original spot before we turned them around
`yarn sync` and `yarn down`
N/A
---
- …
> add script to extract `world.zip` to `.minecraft/saves` folder

- .env.EXAMPLE
- .gitattributes
- .github/workflows/datapack.yml
- .github/workflows/resourcepack.yml
- .github/workflows/scripts.yml
- README.md
- omega-flowey.code-workspace
- package-scripts.js
- package-scripts/modules/ajexport.js
- package-scripts/shared-consts.js
- package-scripts/utils.js
- package-scripts/watch.js
Resolves #103 
---
```sh
yarn start export.force
```
---
N/A
> 🔨 update auto-exporter to AJ `v1.0.0`

- package-scripts/watch.js
- forgot to update them for AJ v1.0.0
---
```sh
yarn start
```
N/A
---
N/A
> 🐛 🔨 update watch script ignored files to AJ `v1.0.0`

- resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/large-side-vine.ajblueprint
- resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/mouth.ajblueprint
- resourcepack/assets/omega-flowey/models/entity/soul/soul.ajblueprint
> - not super needed, but good to have for consistency since every other flowey body model has these tags
Forgot to add tags when making these models.
Will add a linting rule next PR to ensure this isn't missed next time.
---
N/A
N/A
| in-game -- before | in-game -- after | undertale |
| ----------------- | ---------------- | --------- |
|                   |                  |           |
---
N/A
> 🐛 🍱 add missing tags to Flowey body `.ajblueprint`s

- README.md
The contributing steps in README are mostly thorough, but as I was helping @WesLSmith setup his workspace we ran into a couple things that would have been unclear if he was going through setup on his own.
This PR makes some changes to fill in these knowledge gaps.
---
Click to see a preview of the updated README:
https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/blob/2db2b200483ecc28732d3abe334db654fe7cdbf7/README.md
> 📝 cleanup contributor setup steps in `README`

- omega-flowey.code-workspace
this turned out to be super annoying and i don't actually like the terminal in an editor
---
| before | after |
|-|-|
| ![before](https://github.com/user-attachments/assets/7f9ed561-19d7-43a2-b9bb-e745c59cb00a)|![after](https://github.com/user-attachments/assets/f1d1f415-800d-44f4-8080-46ee40cd3fd1)|
> 🧑‍💻 remove default terminal location from `.code-workspace`

- pull_request_template.md
- it was littered with comments that i pretty much deleted everytime. annoying
> 📝 prune PR template steps

- datapacks/omegaflowey/data/minecraft/tags/function/load.json
- datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/summit/player/join_bossfight.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/player/rejoin/check.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/player/rejoin/check/success.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/player/tick.mcfunction
- datapacks/omegaflowey/data/summit/tags/function/join_server.json
see: https://discord.com/channels/511303648119226382/1278138760621723760/1294656738976337950
- https://github.com/TheAfroOfDoom/omegaflowey-minecraft-remastered/commit/a6768d3459d9ac0b7e6a71f53c0059f3c5976175: 🚸 disable natural regen when joining the bossfight
- https://github.com/TheAfroOfDoom/omegaflowey-minecraft-remastered/commit/e03326af1d7d6a92672ec0f9d9552c088cb6904b: 🚸 hook into summit global rejoin checking system
> 🚸 hook into Summit regen/server rejoin logic

- datapacks/omegaflowey/data/omegaflowey.admin/function/help.mcfunction
- datapacks/omegaflowey/data/omegaflowey.admin/function/kill/all.mcfunction
- datapacks/omegaflowey/data/omegaflowey.admin/function/kill/bossfight.mcfunction
- datapacks/omegaflowey/data/omegaflowey.admin/function/kill/decorations.mcfunction
- datapacks/omegaflowey/data/omegaflowey.admin/function/kill/queue.mcfunction
- datapacks/omegaflowey/data/omegaflowey.admin/function/remove_admin.mcfunction
- datapacks/omegaflowey/data/omegaflowey.admin/function/set_admin.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/decorative/remove.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/summit/player/queue/reset.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/summit/setup.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/remove_animated_java_models/summit.mcfunction
- datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/outside/setup.mcfunction
- datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/setup.mcfunction
- package-scripts/build.js
this PR adds a bunch of admin functions relating to omegaflowey entity/logic termination and log management
> 🧑‍💻 add admin functions to ease Summit testing

- package-scripts/build.js
tested the bossfight and player queue on a fresh build world with build packs and everything looked good.
more testing still to be done by the Summit crew, but this is a start
> 📦 update build paths and package Summit packs: `0.1.0`

- datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/setup.mcfunction
required by summit: https://discord.com/channels/511303648119226382/1278138760621723760/1294834680771903509
> 👔 add `summit.booth_decoration` tag to all decorative entities

- datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/shared/arena_box/initialize.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/shared/stop.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/summit/phase/cutscene/terminate/as_bossfight.mcfunction
see individual commit fixes for details on each
> 🐛 fix arena box culling, subsequent intros, nose model

- datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/shared/stop/as_active_player/won.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/shared/stop/as_active_player/won/give_reward_hat_low_hits.mcfunction
- datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/setup/text_displays.mcfunction
3 hits is just impossible with most RNG
> 👔 change special reward hat from <= 3 hits to <= 7 hits

- README.md
https://www.youtube.com/playlist?list=PLg_hm2zl98YuYUUim80MvHCoQ9GJVVtLx
> 📝 add development playlist link to README

- pull_request_template.md
> 📝 remove `# Summary` header from PR template

- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/bullet/states/load_state/resummon.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/executor/initialize.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/executor/states/load_all_states/iterate/summon.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/executor/terminate.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/initialize.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/initialize/on_resummon.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/initialize/on_summon.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/initialize/shared.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/states/load_state.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/states/load_state/blinking_lane.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/states/load_state/manual_summon_blinking_lane.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/states/load_state/resummon.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/states/load_state/resummon/blinking_lane.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/summon.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/indicator/summon/raw.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/player/marker/initialize.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/player/states/save_state.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/start.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines/blinking_lane/initialize.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines/blinking_lane/summon.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines/bullet/preinitialize.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines/indicator/initialize.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines/indicator/initialize/shared.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines/indicator/loop/summon_bullet.mcfunction
- datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/x-bullets-upper-save-states/player/marker/initialize.mcfunction
- datapacks/omegaflowey/data/omegaflowey.main/function/telemetry/data/active_player/gamemode.mcfunction
- datapacks/omegaflowey/data/omegaflowey.main/function/telemetry/data/minify_damage_source.mcfunction
same as https://github.com/TheAfroOfDoom/omegaflowey-minecraft-remastered/pull/273
> i skipped fixing this during the Summit since the demo didn't showcase the attack during it.
> 
> it works now :)
```mcfunction
function _:attack/homing-vines-save-states
```
see https://github.com/TheAfroOfDoom/omegaflowey-minecraft-remastered/pull/91 for visuals + further attack description
> ⚔️ fix `homing-vines-save-states` from summit work

- package-scripts.js
- package-scripts/count-aj-bones.js
- ive had this for awhile in a stash
- used it to optimize/lower bone count for summit
| |
|-|
|![image](https://github.com/user-attachments/assets/29540bfd-c91d-41b6-838d-84a3c1bca04e)|
> 🔨 add script to count AJ blueprint bones

- resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/mouth.ajblueprint
before, it was too smooth. this changes it to use a step graph instead (w/molang) to make it more snappy, closer to how it is in Undertale (looks more violent)
| before | after|
|-|-|
|![before-bb](https://github.com/user-attachments/assets/77810d86-a467-4940-b43e-1e0693534985)|![after-bb](https://github.com/user-attachments/assets/b2a24c8b-a67d-4f6e-94a3-2380ce964c3e)|
||
|-|
|![undertale](https://github.com/user-attachments/assets/c80ac770-44ce-4f93-ad76-688ba440fa83)|
| before | after|
|-|-|
|![image](https://github.com/user-attachments/assets/89fa409b-bbbe-4ff0-8191-8869827482e0)|![image](https://github.com/user-attachments/assets/cfa938d1-e741-4d66-8bfa-1fa1da5d0d75)|
> 💫 make mouth laugh animation more snappy
