TheAfroOfDoom/omegaflowey-minecraft-remastered

datapacks/omega-flowey/data/_/functions/README.md
datapacks/omega-flowey/data/_/functions/attack/random/0.mcfunction
datapacks/omega-flowey/data/entity/functions/directorial/boss_fight/vanilla/phase/attack/initialize/0.mcfunction
datapacks/omega-flowey/data/entity/functions/directorial/boss_fight/vanilla/phase/attack/terminate.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/attack_phase/0.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/choose_attack.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/choose_attack/dentata-snakes.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/choose_attack/friendliness-pellets.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/choose_attack/homing-vines.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/choose_attack/x-bullets-lower.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/choose_attack/x-bullets-upper.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/reduce_weights.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/remove_previous_tags.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/start.mcfunction

Previously, when running the `random` attack repeatedly often we'd see attacks repeated back-to-back, e.g. spamming `friendliness-pellets` 3x in a row.
While this was technically still "random", it didn't _feel_ random. It can feel like the map is almost broken when a specific attack repeats more than twice back-to-back.
From [CavemanFilm's video](https://youtu.be/k9d7zWBSuSw?t=304) where the `friendliness-pellets` attack occurs 4x in a row:
> Oh wow you're just spamming those!
Now he actually _does_ mix up his attacks...
The player had to clarify for the video that the attacks are indeed randomized since it doesn't necessarily _feel_ random due to just how many times it spammed the single attack.
To fix this, we can adjust the weight of an attack so that it's less likely to repeat if we …

add support for `random` attack to consider previous trials

---

.github/workflows/test.yml
.github/workflows/validate.yml
.gitmodules
README.md
datapacks/omega-flowey/data/utils/functions/math/max.mcfunction
datapacks/omega-flowey/data/utils/functions/math/min.mcfunction
datapacks/omega-flowey/data/utils/tests/math/max.mcfunction
datapacks/omega-flowey/data/utils/tests/math/min.mcfunction
pull_request_template.md

This PR adds support for `.mcfunction` unit tests via the [packtest](https://github.com/misode/packtest) and [packtest_runner](https://github.com/CarbonSmasher/packtest_runner) repos. See this [sample repo](https://github.com/misode/packtest-runner-example) for another example (that was used here) to get tests to run in CI.
- adds github workflow to run `packtest`
- adds unit tests for `utils:math/max` and `utils:math/min` functions
- updates `README.md` with instructions for how to install the modded client required to run tests locally
- updates the pull request template to include a `Test plan` section
---
```mcfunction
test runall
```
see this PR's commit history and the corresponding CI statuses (❌'s and ✔️'s)
---
- world sync (pre-opening world with modded client)

add support for unit testing

---

.github/workflows/validate.yml
datapacks/omega-flowey/data/omega-flowey/tests/reset/should_wipe_scores.mcfunction
datapacks/omega-flowey/data/omega-flowey/tests/setup/should_add_teams.mcfunction
datapacks/omega-flowey/data/omega-flowey/tests/setup/should_reset_group_ids.mcfunction
datapacks/omega-flowey/data/utils/functions/math/vector/dot_macro.mcfunction
datapacks/omega-flowey/data/utils/tests/math/max.mcfunction
datapacks/omega-flowey/data/utils/tests/math/min.mcfunction
datapacks/omega-flowey/data/utils/tests/math/vector/dot.mcfunction

This PR adds unit tests for:
- `utils:math/vector/dot`
- `omega-flowey:reset`
- `omega-flowey:setup`
**NOTE**: the tests for `utils:math/vector/dot` revealed that the function isn't perfect (it's non-commutative), but that's fine for now since it's unclear if we even want to use it (for the `homing-vines` attack's hitbox).
This PR also updates to the fixed `packtest_runner` version from https://github.com/CarbonSmasher/packtest_runner/pull/1 that includes support for specifying a custom `packtest` version to use (allowing us to update the variable for new `packtest` features instead of waiting on `packtest_runner` to update).
---
see **Summary** ^
unit tests pass
In the modded client run:
```mcfunction
test runall
```
N/A
---
N/A

add unit tests for `utils:math/vector/dot`, `omega-flowey:reset`, and `omega-flowey:setup`

---

.github/workflows/validate.yml
README.md
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/dentata-snakes/bullet/loop.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/dentata-snakes/bullet/loop/bounce.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/dentata-snakes/executor/terminate/boss_fight.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/dentata-snakes/reset_scores.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/friendliness-pellets/executor/loop/summon_indicator.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/friendliness-pellets/executor/terminate/boss_fight.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/friendliness-pellets/indicator/loop.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/friendliness-pellets/reset_scores.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/homing-vines/bullet/loop.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/homing-vines/executor/terminate/boss_fight.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/homing-vines/indicator/initialize.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/homing-vines/reset_scores.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/executor/initialize/effects.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/executor/terminate/boss_fight.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/indicator/loop/summon_bullet.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/indicator/terminate.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/reset_scores.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/start.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-upper/executor/initialize/effects.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-upper/executor/terminate/boss_fight.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-upper/indicator/loop/summon_bullet.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-upper/indicator/terminate.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-upper/reset_scores.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-upper/start.mcfunction
datapacks/omega-flowey/data/entity/functions/utils/damage.mcfunction
datapacks/omega-flowey/data/entity/functions/utils/shake_screen.mcfunction
datapacks/omega-flowey/data/utils/functions/math/vector/dot.mcfunction
scratch.txt

**closes #11**
We compiled a handful of TODOs in the codebase so far that did not have an associated [issue](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/issues).
This PR creates an issue for each one and updates the TODO comment in the code to reference it.
Example:
https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/blob/1c7d513afea22f21e875fc48f7c413149b8fa3a3/datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/friendliness-pellets/indicator/loop.mcfunction#L5-L9
https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/issues/45
Effort was put in to ensure each issue had a reasonable description and could be picked up without too much more clarification.
Going forward, **no TODOs will be merged without an associated …

ticketize current TODOs in codebase

---

.github/workflows/datapack.yml

Misode made a workflow that can run PackTest without any special third party code. Just some simple `curl`s in a shell script (the workflow file itself) and it runs much faster than before with `packtest_runner`.
- see: https://discord.com/channels/154777837382008833/1185733502294044802/1190466881488945162
interestingly it seems like caching is already implemented/not worth implementing in most of the download/install steps. After the actual server starting + running tests, all the other steps are 1s or 0s.
So it's either already caching (likely) or doesn't even need it if its not.
---
tests still run as expected. runtime goes from >2m to ~30s.
N/A
see workflow runs associated with this branch's commits
---
N/A

upgrade `PackTest` workflow to simplier + faster version

---

README.md

Our readme is pretty barebones right now, so this PR aims to fill it in a bit more with tools that we prefer to use for 3d modelling/image editing/etc. and steps we recommend developers follow when creating a new Animated Java model/animation.
---
N/A
N/A
go to [README.md](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/blob/719a7778b3096a22d820264d6ca4a52c41a02ad5/README.md) to see the updated README rendered
---
N/A

add recommended tools and new model steps to README

---

datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/attack_phase/0.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/reduce_weights.mcfunction

Currently, we reduced the weight of the previously-ran attack through the `random` attack from `2` -> `1`.
#29 has more details, but as an example:
if the base weights for attacks were:
| attack | x-bullets-lower | x-bullets-upper | finger-guns |
|-|-|-|-|
| base weight | 2 | 2 | 2 |
| probability of being chosen | 33% | 33% | 33% |
and we run the `random` attack -> it runs `finger-guns`, the weights/probabilities become:
| attack | x-bullets-lower | x-bullets-upper | finger-guns |
|-|-|-|-|
| weight | 2 | 2 | 1 |
| probability of being chosen | 40% | 40% | 20% |
in this PR, we increase the base weights from `2` -> `3` and increase the weight reducer from `1` -> `2`. this changes the previously-ran attack table to:
| attack | x-bullets-lower | x-bullets-upper | finger-guns |
|-|-|-|-|
| …

increase weight reducer of "previous_trials" logic for random attacks

---

package-scripts/sync-world.js

- fixes #93
I tried to setup the repo on a new laptop and `yarn down` failed with:
```
[Error: ENOENT: no such file or directory, stat 'C:\Users\tehaf\AppData\Roaming\.minecraft\saves\omega-flowey-remastered']
```
This PR fixes that issue by checking to see if the world save actually exists before performing any operations around it.
---
Runs locally if you don't have a world save with the map name in your Minecraft `saves` directory (e.g. `omega-flowey-remastered`)
1. backup your local world save manually
2. delete your local world save
3. run `yarn down`
N/A
---
N/A

fix `yarn down` not extracting world to saves directory if world save doesn't already exist

---

datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/dentata-snakes/bullet/initialize/tail_macro.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/flies/executor/initialize/indicator/error.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/random/error/zero_sum.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-lower/executor/initialize.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-shared/executor/initialize/error.mcfunction
datapacks/omega-flowey/data/entity/functions/hostile/omega-flowey/attack/x-bullets-upper/executor/initialize.mcfunction

- closes #48
---
```mcfunction
function _:attack/x-bullets-upper
```
| error message |
|-|
|![preview](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/assets/13565346/e6551a86-6629-48ba-8f95-653d0d1ccbe3) |
---
- specify error function parameters directly after function call instead of in storage: https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/536b08a016c2b4ee7da1b94a54573753fe1b9e30
- didn't realize when i made these commands you could specify macro parameters directly
- tested each error to make sure they still appear as expected

🥅 Print error when trying to start `x-bullets` attack without eye model

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/bomb/bullet/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/bomb/indicator/loop/bullet/summon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/dentata-snakes/bullet/initialize/head.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/dentata-snakes/indicator/loop/summon_bullet.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/bomb.ajblueprint

This PR migrates the necessary AJ blueprints to re-enable the `bomb` attack for Minecraft 1.21.
The only model needed to migrate was `bomb.ajblueprint`.
Tested in-world and the attack functions and looks as expected visually, with one caveat:
Until https://github.com/Animated-Java/animated-java/issues/190 is fixed and released in an AJ pre-release, the bombs will summon with the wrong variant. This makes them have a little orange cube from the `explode` variant as they fall.
I ran the AJ exporter locally with the above bug fixed and the above issue was resolved.
---
```mcfunction
function _:attack/bomb
```
---
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/e1458b3a8451369659d0971ccaa7c908273cdfbe: ♻️ Use AJ 1.0.0 summon args to summon `dentata-snake-ball` head …

⬆️ ⚔️ migrate `bomb` AJ model to AJ `v1.0.0-pre3`

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/finger-guns/bullet/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/finger-guns/executor/loop/indicator/summon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/finger-guns/indicator/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/finger-guns/indicator/loop/bullet/summon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/finger-guns/indicator/loop/laser/summon.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-bullet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-laser.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun.ajblueprint

This PR migrates the necessary AJ blueprints to re-enable the `finger-gun` attack for Minecraft 1.21.
The models we needed to migrate were `finger-gun`, `finger-gun-bullet`, and `finger-gun-laser`.
---
```mcfunction
function _:attack/finger-guns
```
---
N/A

⬆️ ⚔️ migrate `finger-gun` attack to AJ v1.0.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/friendliness-pellets/bullet/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/friendliness-pellets/indicator/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/friendliness-pellets/indicator/loop/summon_bullet.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/friendliness-pellet-ring.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/friendliness-pellet.ajblueprint

This PR migrates the necessary AJ blueprints to re-enable the `friendliness-pellets` attack for Minecraft 1.21.
The models we needed to migrate were `friendliness-pellet` and `friendliness-pellet-ring`.
---
```mcfunction
function _:attack/friendliness-pellets
```
---
N/A

⬆️ ⚔️ migrate `friendliness-pellets` attack to AJ v1.0.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/homing-vines/blinking_lane/summon/raw.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/homing-vines/bullet/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/homing-vines/indicator/loop/summon_bullet.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine-blinking-lane.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine.ajblueprint

This PR migrates the necessary AJ blueprints to re-enable the `homing-vines` attack for Minecraft 1.21.
The models we needed to migrate were `homing-vine` and `homing-vine-blinking-lane`.
---
```mcfunction
function _:attack/homing-vines
```
---
N/A

⬆️ ⚔️ migrate `homing-vines` attack to AJ v1.0.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/flies/executor/initialize/indicator/summon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/flies/indicator/loop/bullet/summon.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/housefly.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/venus-fly-trap.ajblueprint

This PR migrates the necessary AJ blueprints to re-enable the `flies` attack for Minecraft 1.21.
The models we needed to migrate were `housefly` and `venus-fly-trap`.
---
```mcfunction
function _:attack/flies
```
---
N/A

⬆️ ⚔️ migrate `flies` attack to AJ v1.0.0

---

datapacks/omega-flowey/data/entity/function/directorial/boss_fight/vanilla/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/directorial/boss_fight/vanilla/phase/soul/loop/next_event.mcfunction
datapacks/omega-flowey/data/entity/function/directorial/boss_fight/vanilla/phase/soul/static/as_root.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/soul/tv_screen.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/tv-screen/default.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/warning/tv_screen.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/friendliness-pellets/indicator/loop.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon/soul/tv_screen.mcfunction
package-scripts/watch.js
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/tv-screen.ajblueprint

This PR migrates the `tv-screen` AJ model file so we can summon it in-game again for Minecraft 1.21.
---
```mcfunction
```
---
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/5fd330bfee7a728dfe7bbacc09a878a130df3b99: 🗑️ Disable deleteStaleExportFiles 
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/5d60eaabd1645aedffa61c020627685850e56be3: 🐛 Update missed `friendliness_pellet_ring` variant syntax

⬆️ 🍱 migrate `tv-screen` model to AJ v1.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-upper/executor/loop/pause_eye.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-upper/executor/terminate.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-upper/indicator/loop/summon_bullet.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-upper/indicator/terminate.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/upper-eye.ajblueprint

This PR migrates the `upper-eye` AJ model file so we can summon it in-game again for Minecraft 1.21.
---
```mcfunction
```
---
N/A

⬆️ 🍱 migrate `upper-eye` model to AJ v1.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/executor/loop/pause_eye.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/executor/terminate.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/indicator/loop/summon_bullet.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/indicator/terminate.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/lower-eye.ajblueprint

This PR migrates the `lower-eye` AJ model file so we can summon it in-game again for Minecraft 1.21.
---
```mcfunction
```
---
N/A

⬆️ 🍱 migrate `lower-eye` model to AJ v1.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/nose.ajblueprint

This PR migrates the `nose` AJ model file so we can summon it in-game again for Minecraft 1.21.
---
```mcfunction
```
---
N/A

⬆️ 🍱 migrate `nose` model to AJ v1.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/large-side-vine.ajblueprint

This PR migrates the `large-side-vine` AJ model file so we can summon it in-game again for Minecraft 1.21.
---
```mcfunction
```
---
N/A

⬆️ 🍱 migrate `large-side-vine` model to AJ v1.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/petal_pipe_circle/default.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/petal_pipe_circle/disabled.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/pipe/soul_0.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/pipe/soul_1.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/pipe/soul_4.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/animate/pipe/soul_5.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/petal_pipes/petal-pipe-circle.ajblueprint

This PR migrates the `petal-pipe-circle` AJ model file so we can summon it in-game again for Minecraft 1.21.
---
```mcfunction
```
---
N/A

⬆️ 🍱 migrate `petal-pipe-circle` model to AJ v1.0

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/indicator/loop/summon_bullet.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-upper/indicator/loop/summon_bullet.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/projectile-star.ajblueprint

This PR re-enables both `x-bullets` attacks for Minecraft 1.21.
We only needed to migrate the `projectile-star` model since we did the other migration work for the `upper-eye` and `lower-eye` models in #105 and #106.
---
```mcfunction
function _:attack/x-bullets-upper
```
---
N/A

⬆️ ⚔️ migrate `x-bullets-lower` and `x-bullets-upper` attacks to AJ v1.0.0

---

datapacks/omega-flowey/data/entity/function/soul/soul_0/soul/saved.mcfunction
resourcepack/assets/omega-flowey/models/entity/soul/soul.ajblueprint

This PR migrates the `soul` AJ model file so we can summon it in-game again for Minecraft 1.21.
---
```mcfunction
function _:boss_fight
```
---
N/A

⬆️ 🍱 migrate `soul` model to AJ v1.0

---

.gitignore
package-scripts.js
package-scripts/linting-rules/correct-ajblueprint-settings.js
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/bomb.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/dentata-snake-ball.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-bullet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-laser.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/friendliness-pellet-ring.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/friendliness-pellet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine-blinking-lane.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/housefly.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/projectile-star.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/venus-fly-trap.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/large-side-vine.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/lower-eye.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/nose.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/petal_pipes/petal-pipe-circle.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/petal_pipes/petal-pipe-middle.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/tv-screen.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/upper-eye.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/act-button.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-0-bandaid.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-0-sword.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul.ajblueprint

AJ had some formatting changes from the last used prerelease in https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/113 to AJ v1.0.0-pre11 (current).
We are explicitly updating the format of these files here so the auto-export script can be updated cleanly. (https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/issues/103)
---
All Minecraft attacks/functions should behave as expected (tested locally and they look good!)
---
N/A

⬆️ 🍱 migrate `.ajblueprints` to AJ `v1.0.0-pre11`

---

README.md
package-scripts.js
package-scripts/watch.js
package.json
yarn.lock

I never use this and we don't really recommend using it anyway.
Original motivation was so you didn't need to manually run `yarn start export`, but that's easy enough to do if you run into an issue in-game.
---
I tested `yarn start` and ensured in-game assets/functions still worked.
---
```sh
yarn start
```
N/A
---
N/A

🔥 Delete `watch.models` logic

---

package-scripts/sync-world.js
package-scripts/watch.js

On Windows 11 (or at least on my laptop), important dev scripts fail when `fs-extra.remove()` is called. These scripts were:
- `yarn start`
- `yarn down`
To fix this, we switch to the `rimraf` package since it's cross-platform.
---
1. use a known problematic OS (Windows 11)
2. run either `yarn start` or `yarn down`
3. see error
N/A
---
N/A

🐛 🔨 Fix platform inconsistency with file removal in dev scripts

---

package-scripts/linting-rules/correct-ajblueprint-settings.js

This is a follow-up to https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/114.
In AJ v1.0.0, setting a path (e.g. `blueprint_settings.data_pack`) through Blockbench doesn't leave a trailing slash in the JSON file anymore.
Old (migrated) models still have this trailing slash. Both are valid, however, so our linting rule should accept paths with/without the trailing slash.
---
```sh
yarn lint
```
N/A
---
N/A

🐛 🚨 make trailing slash in datapack setting linter optional

---

package-scripts/linting-rules/correct-ajblueprint-settings.js

A follow-up to https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/125 to prevent it from happening in the future
---
i set the `summon_commands` property in `bomb.ajblueprint` to an empty string to test the lint rule:
---
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/e78bcfdf08d8ef6c39cd10b01191b6797e86a6aa: ♻️ refactor `correct-ajblueprint-settings` to use guard clauses

🚨 🍱 add lint rule to prevent empty summon commands in models

---

datapacks/omega-flowey/data/utils/function/error.mcfunction
datapacks/omega-flowey/data/utils/function/log.mcfunction

This will be used in a follow-up PR for nicer logs on `/reload`.
---
view pre-existing errors with:
```mcfunction
function _:reset
function _:attack/x-bullets-upper
```
For the given command:
```mcfunction
function utils:log { text_component: '"test"'}
```
The chat outputs:

♻️ Refactor log prefix out of `error` function and into generic `log` function

---

README.md
datapacks/omega-flowey/data/entity/function/reset.mcfunction
datapacks/omega-flowey/data/entity/function/setup.mcfunction
datapacks/omega-flowey/data/minecraft/tags/function/load.json
datapacks/omega-flowey/data/omega-flowey/function/reset.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/setup.mcfunction
datapacks/omega-flowey/data/omega-flowey/test/reset/should_reset_group_ids.mcfunction
datapacks/omega-flowey/data/omega-flowey/test/reset/should_wipe_scores.mcfunction

If you were to switch to a branch with new e.g. `objectives` and forgot to manually run the `_:setup` function, you could easily get missing behavior due to said new objectives not existing.
This PR ensures that won't happen since in order to get the new functions/behavior you have to `/reload`, which will always run the base `setup` function.
---
```mcfunction
reload
```
also added a log on `reload` so it's clear :)
---
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/0ddb690bc278f3744bd3eb4d8a049ef150fc6f3e: 🐛 Fix wrong batch name for `reset` tests
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/4c3f2151aecbf795fb3bb89bca1363e9cf131190: ✅ Move "reset group IDs" behavior from `setup` to `reset` function
- …

🧑‍💻 run `setup` function on `/reload`

---

datapacks/omega-flowey/data/entity/function/soul/soul_0/bandaid/summon.mcfunction
datapacks/omega-flowey/data/entity/function/soul/soul_0/bullet/initialize/saved.mcfunction

- closes #89 
This PR adds random jitter to Y axis values of soul_event0 Bandaid spawns to substantially reduce the clipping occuring from overlapping bandaid entities. The range of value allowed has to be relatively large as sub 1 unit changes still frequently result in clipping. Ugly clipping can still occur with this patch though its frequency should be dramatically reduced 
| before |
|-|
| ![image](https://github.com/user-attachments/assets/333da32f-90f8-45b9-8191-5fee27500767) |
---
|after|
|-|
| ![javaw_oAUOzViotB](https://github.com/user-attachments/assets/474dddc6-d945-4caf-9430-e7a1f0d2527c) ![javaw_vqbeM1Lh3a](https://github.com/user-attachments/assets/6972f825-89e3-4480-9a2b-d0907859fec5) |

🐛 👻 randomize `soul-0-bandaid` height to minimize overlapping

---

datapacks/omega-flowey/data/omega-flowey/test/setup/should_log_initialized_message.mcfunction

A chat message was added to the `setup` function so that you'd get direct feedback that the datapack successfully loaded when you ran `/reload`.
I wanted to add a test for this in https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/129 but couldn't get it to pass in CI.
The fix was to add the `# @dummy` test directive so the test server would find a player for the `tellraw` to have been sent to.
---
In the test client:
```mcfunction
test runall
```
CI passes :)

✅ Add unit test for `Datapack initalized` message upon setup

---

.vscode/extensions.json
omega-flowey.code-workspace

Once Spyglass has formatting/CLI we can just catch this in CICD, but for now we should make it easier for contributors to remove trailing whitespace without having to think about it.
---
- also add `Trailing Spaces` extension to recommended extensions list make them visible + obvious

🔧 make VSCode trim trailing whitespace on save

---

resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/bomb.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/dentata-snake-ball.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-bullet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-laser.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/friendliness-pellet-ring.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/friendliness-pellet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine-blinking-lane.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/housefly.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/projectile-star.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/venus-fly-trap.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/large-side-vine.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/lower-eye.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/mouth.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/nose.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/petal_pipes/petal-pipe-circle.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/petal_pipes/petal-pipe-middle.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/tv-screen.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/upper-eye.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/act-button.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-0-bandaid.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-0-sword.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-5-bullet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-5-crosshair.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-5-flower.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-5-gun.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul.ajblueprint

This is just opening each `.ajblueprint` in the latest AJ version on the Blockbench store (v1.1.0) and saving.
Fortunately there's no significant diffs :)

⬆️ migrate model files to AJ `v1.1.0`

---

datapacks/omega-flowey/data/_/function/reset_scores.mcfunction
datapacks/omega-flowey/data/entity/function/reset_scores.mcfunction
datapacks/omega-flowey/data/entity/function/setup.mcfunction

we incorrectly assumed every `reset_scores.mcfunction` would be under the `attack` directory. but soul events also exist.
this assumption led to us forgetting to call `function entity:soul/reset_scores` upon setup (`/reload`).
this PR refactors these functions so there's now a top-level `entity:reset_scores` function that is guaranteed to reset all parameters upon `/reload`

🐛 fix `entity:setup` not resetting soul event params

---

datapacks/omega-flowey/data/entity/function/soul/soul_5/indicator/locator.mcfunction

When `soul-5-gun`'s hitbox touches a player, it slightly damages them (to prevent cheesing the event by standing inside the gun).
After soul event 5 transitions to `SAVED` and the gun starts shooting flowers / healing the player, it should no longer damage the player upon contact.
Before, it would damage the player post-SAVED. This PR fixes this so it no longer damages the player post-SAVED.
---
```mcfunction
function _:soul/5
```
| before | after |
|-|-|
|![before](https://github.com/user-attachments/assets/f54d8e50-a1d2-4586-b0d2-d6a0e2fe7ee5)|![after](https://github.com/user-attachments/assets/2d313f75-7a92-472f-8e40-e88165dbef18)|

🐛 👻 fix `soul-5-gun` hitbox damaging players post-SAVED

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-upper/reset_scores.mcfunction

In Undertale, the cone that the upper x-bullets summon towards the player in a cone that leds to the player needing to slowly move horizontally in order to:
- avoid the bullet directly approaching them
- avoid walking into the bullet to the left/right of them
Currently this attack's cone size in the map is too wide, so the player can just sprint horizontally at full speed without any movement nuance.
This PR decreases the cone size from `39` to `27` degrees so the attack isn't trivially easy to dodge.
(I think the original `39` degrees came from a sort-of measurement of the cone in Undertale, but that's less important than the attack's actual behavior in Minecraft)
---
```mcfunction
```
| in-game -- before | in-game -- after | undertale |
| …

⚔️ decrease `x-bullets-upper` attack cone size

---

resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/bomb.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/dentata-snake-ball.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-bullet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-laser.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/friendliness-pellet-ring.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/friendliness-pellet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine-blinking-lane.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/housefly.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/projectile-star.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/venus-fly-trap.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/large-side-vine.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/lower-eye.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/mouth.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/nose.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/petal_pipes/petal-pipe-circle.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/petal_pipes/petal-pipe-middle.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/tv-screen.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/upper-eye.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/act-button.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-0-bandaid.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-0-sword.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-5-bullet.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-5-crosshair.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-5-flower.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul-5-gun.ajblueprint
resourcepack/assets/omega-flowey/models/entity/soul/soul.ajblueprint

Opens each `.ajblueprint` in the latest AJ version on the Blockbench store (v1.3.0) and saving.
There was a bug with the `projectile_star` model that prevented it from auto-exporting. This was fixed: 6d598714e81adad0eaffd400d3fb1757d2360d32
---
```sh
yarn start export
```

⬆️ migrate model files to AJ `v1.3.0`

---

.github/variables/shared.env
.github/workflows/datapack.yml
.github/workflows/resourcepack.yml
.github/workflows/scripts.yml

GitHub Actions doesn't support sharing environment variables between workflows natively, but we can use some simple code in the following Action to accomplish this:
https://github.com/tw3lveparsecs/github-actions-set-variables
Now we don't have to copy-paste each environment variable into each workflow config file (DRY)
---
see workflows passing

♻️ DRY common workflow env variables

---

.github/actions/setup-yarn/action.yml
.github/workflows/datapack.yml
.github/workflows/resourcepack.yml
.github/workflows/scripts.yml

Our GitHub Actions workflows that used Yarn shared a lot of steps in-common related to downloading yarn, installing dependencies (from cache), and setting up environment variables.
This PR DRYs this up so the workflows now used shared config code in one place under `./.github/actions/setup-yarn`:
https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/blob/2be7c6fa09406243f03116333ffdff10d2bb48d2/.github/actions/setup-yarn/action.yml#L1-L20
see passing CICD

♻️ 👷 DRY common yarn setup steps into local action

---

.github/actions/setup-animated-java-exports/action.yml
.github/actions/setup-animated-java-exports/install-animated-java-and-run-auto-exporter.sh
.github/workflows/datapack.yml
package-scripts.js
package-scripts/modules/ajexport.js

(this is a cool one)
Resolves #81 -- see ticket for full context
This PR adds workflow/CICD support for AJ export files. Since we previously removed AJ export files from the repository (by adding them to `.gitignore`), no CICD jobs could reference them. This was particularly relevant for the MC unit test job (`datapack/test`).
Now, the `datapack/test` job sets up AJ export files prior to running. It attempts to restore from a cache key comprising of:
- AJ version
- Blockbench version
- the checksum of every `.ajblueprint` file in the repo
So if all of the above properties stay the same, it will restore from cache and not go through the entire Blockbench install + AJ export process.
---
If the cache does NOT hit, we do the following:
1. Download Blockbench
2. Install Blockbench and related …

✨ 👷 generate AJ export files in `datapack/test` CI job

---

.github/actions/setup-animated-java-exports/action.yml
.gitignore
datapacks/animated_java/data/animated_java/test/ensure_summonable/act_button.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/bomb.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/dentata_snake_ball.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/finger_gun.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/finger_gun_bullet.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/finger_gun_laser.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/friendliness_pellet.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/friendliness_pellet_ring.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/homing_vine.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/homing_vine_blinking_lane.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/housefly.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/large_side_vine.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/lower_eye.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/mouth.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/nose.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/petal_pipe_circle.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/petal_pipe_middle.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/projectile_star.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/soul.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/soul_0_bandaid.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/soul_0_sword.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/soul_5_bullet.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/soul_5_crosshair.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/soul_5_flower.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/soul_5_gun.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/tv_screen.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/upper_eye.mcfunction
datapacks/animated_java/data/animated_java/test/ensure_summonable/venus_fly_trap.mcfunction

This is the first set of tests that rely on https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/ad93d9d2ac2b12601cf4f60af95db283e8f4d5de.
After the CI job runs the auto exporter and generates AJ export files, we can reference them in our unit tests.
These tests perform very basic "can we actually summon and reference the model entity?" checks.
---
```
test runall
```
The tests live under `datapcks/animated_java/data/animated_java/test`, so we had to update `.gitignore` to be more specific as to what files are actually AJ export files.

✅ add tests to verify each AJ model is summonable

---

.github/workflows/datapack.yml

- we get log changes/errors that block the CICD AJ export process on beta versions since there are new beta versions available.
- quick and easy fix for this is to upgrade to the latest beta release of Blockbench
---
see failing CICD `datapack/test` before. it passes after

⬆️ 💚 upgrade Blockbench in CICD to `4.11.0-beta.3`

---

package-scripts.js
package-scripts/sync-world.js

For Smithed Summit, it will be helpful for the sync script to support backing up the schematic world we'll be building on.
---
```
yarn node ./package-scripts/sync-world --up --world-path="C:\Users\afro\AppData\Roaming\.minecraft\saves\some-world" --backup-path="./world-a.zip"
yarn node ./package-scripts/sync-world --up --world-path="C:\Users\afro\AppData\Roaming\.minecraft\saves\world-sync-test" --backup-path="./world-a.zip"
```
N/A

🔨 update world sync script to accept arbitrary paths

---

.github/workflows/datapack.yml

prior version `1.3.0` had a bug where it wouldn't output variant functions correctly.
see: https://github.com/Animated-Java/animated-java/releases/tag/v1.4.0

⬆️ upgrade AJ in CICD to `v1.4.2`

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon/soul/tv_screen.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon/soul/tv_screen/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon/tv_screen/initialize.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/setup.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/summit/room/setup.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/summit/room/setup/outside.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/summit/room/setup/outside/tv_screen.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/tv-screen.ajblueprint

This PR adds functions we can use going forward to store display entity summon commands concretely in the repo, instead of just being entities that live in the binary world zip.
For now, we add summon + initialize commands for the `tv-screen` model that is floating above our Summit booth.
---
```mcfunction
/reload
/function omega-flowey:setup
/function omega-flowey:summit/room/setup
```
||
|-|
|![2024-09-20_22 39 31](https://github.com/user-attachments/assets/1f6ea82b-5198-4307-ba21-5d3c405dbc8a)|
---
- [`0d53b52` (#173)](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/173/commits/0d53b52b90949704eda656f72ab44ffb29386018): ♻️ add `tv-screen-new` tag to tv_screen AJ models

✨ add room setup logic and summon `tv-screen` model outside

---

.vscode/extensions.json
omega-flowey.code-workspace

In the past I've manually found emojis commonly relevant to Flowey development and pasted them in commit titles:
- ⚔️ attacks: https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/18db7dc02a9aa8b3954131464dbeb79aebd39890
- 👻 soul events: https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/ebf866f814f60653b0701cbb20f3321ff84555f0
- 🎲 randomization: [`e737865` (#118)](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/118/commits/e737865e5cfcc1e41b2244a733d391dd592c3a15)
- 📋 copy-pasting files/code: [`825742a` (#175)](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/175/commits/825742a051b4c6983bf86b4661c61a8f706461ad)
turns out we can add these to the …

🧑‍💻 add custom Gitmoji icons

---

resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/nose.ajblueprint

- AJ v1.4.1 included a fix that made pre/post keyframes work properly
- this made me realize the step frames in `nose/move` was causing the animation to look bad/janky
- changing from `step` to `linear` and properly configuring the pre/post keyframes gives us a  nostril animation that looks better than before (likely close to what we originally intended in the animation)
---
```mcfunction
function _:boss_fight
```
| before (post AJ v1.4.1) | after (fixed) |
|-|-|
|![before - bug](https://github.com/user-attachments/assets/177525eb-0b61-4f8c-a2d7-db1cd39f833d)|![after](https://github.com/user-attachments/assets/9baa594a-7e15-4607-bb5f-872d7c78211d)|
| before (pre AJ v1.4.1) | Undertale |
|-|-|
|![](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/assets/13565346/17568587-b …

🐛 💫 update `nose/move` animation step frames

---

.github/actions/setup-animated-java-exports/install-animated-java-and-run-auto-exporter.sh
datapacks/omega-flowey/data/_/function/summon.mcfunction
datapacks/omega-flowey/data/entity/function/directorial/boss_fight/summit/start.mcfunction
datapacks/omega-flowey/data/entity/function/directorial/boss_fight/tick.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/friendliness-pellets/executor/loop/summon_indicator.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/homing-vines/bullet/loop.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/homing-vines/indicator/initialize/randomize_bullet_position.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/homing-vines/indicator/initialize/randomize_indicator_position.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/homing-vines/indicator/loop/presummon_bullet/face_player_location.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/homing-vines/indicator/loop/visualize_blinking_lane.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/indicator/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/indicator/initialize/face_player.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/start.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-upper/start.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/summon/relative.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/summit/room/setup.mcfunction
package-scripts.js
package-scripts/sync-world.js
package.json
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine-blinking-lane.ajblueprint

Plan atm is to only use attacks from `vanilla` phase 0, so this PR makes sure each one runs and summons entities/bullets/etc. as expected.
This includes:
- `friendliness-pellets`
- `homing-vines`
- `x-bullets-lower`
- `x-bullets-upper`
We also fix some non-position-related bugs for these attacks
---
```mcfunction
function _:attack/friendliness-pellets
function _:attack/homing-vines
function _:attack/x-bullets-upper
```
see recording of every attack: https://youtu.be/BKPU9toZt6M
---
- [`dfb452c` (#179)](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/179/commits/dfb452ce91dddb831b1fad11813a43c759b2ab10): 📦 sync summit world
- [`2ddea54` (#179)](https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/ …

📍 ⚔️ update phase 0 attack coordinates for Summit world

---

datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/bomb/bullet/loop.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/bomb/bullet/loop/stop_falling.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/bomb/indicator/loop/bullet/presummon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/bomb/indicator/loop/bullet/summon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/dentata-snakes/bullet/loop.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/dentata-snakes/bullet/loop/maybe_bounce.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/dentata-snakes/indicator/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/dentata-snakes/indicator/loop/summon_bullet.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/finger-guns/executor/loop/indicator/presummon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/finger-guns/indicator/loop/bullet/summon.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/finger-guns/indicator/loop/laser/summon.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/finger-gun-laser.ajblueprint
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/attacks/homing-vine-blinking-lane.ajblueprint

In the event we want to mix-in some of attack phase 1's attacks to the Summit boss, I fixed them up here so they spawn properly.
These attacks are:
- `bomb`
- `dentata-snakes`
- `finger-guns`
We specifically chose to skip the `flies` attack here since the animations for it are far from complete (missing `venus_fly_trap` model growing animation).
We also fix a bug with the finger gun's laser, similar to the bug with homing-vines blinking-lane from https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/pull/179.
---
```mcfunction
function _:attack/bomb
function _:attack/dentata-snakes
function _:attack/finger-guns
```
see recording of individual attacks: https://youtu.be/e3QUNXO8IPk
(note: video doesn't include the finger-guns laser bug fix)
---
- [`29e5016` …

📍 ⚔️ update attack phase 1 coordinates for Summit world

---

datapacks/omega-flowey/data/entity/function/soul/shared/call_for_help_display/summon.mcfunction
datapacks/omega-flowey/data/entity/function/soul/soul_5/crosshair/summon.mcfunction
datapacks/omega-flowey/data/entity/function/soul/soul_5/indicator/initialize/saved.mcfunction
datapacks/omega-flowey/data/entity/function/soul/soul_5/indicator/loop/aiming/next_crosshair/randomize_yaw/check_valid.mcfunction
datapacks/omega-flowey/data/entity/function/soul/soul_5/indicator/summon.mcfunction
datapacks/omega-flowey/data/entity/function/soul/soul_5/shared/terminate_unless_in_region.mcfunction

We plan on showcasing soul event 5 (gun) during the Summit. To facilitate this, we update the hard-coded coordinates to the new Summit arena's rotation and (temporary) position.
---
```mcfunction
function _:soul/5
```

📍 👻 update `soul_5` summon coordinates

---

.gitignore
.spyglassrc.json

this will prevent:
- the `build` directory from being parsed on project load
- our MC unit tests from raising IDE errors falsely (since they use modded commands from packtest)
- note all this requires being on my custom spyglass branch until it's merged:
https://github.com/TheAfroOfDoom/Spyglass/tree/watcher-ignore-exclude-config
---
overall generally much faster Spyglass load times, and probably faster performance in general since we're not watching nearly as many files

🔧 add `.spyglassrc.json` and exclude patterns

---

datapacks/omega-flowey/data/entity/function/directorial/boss_fight/shared/stop/as_active_player.mcfunction
datapacks/omega-flowey/data/entity/function/directorial/boss_fight/summit/phase/soul/terminate/final.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/friendliness-pellets/executor/terminate/boss_fight.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-lower/executor/terminate/boss_fight.mcfunction
datapacks/omega-flowey/data/entity/function/hostile/omega-flowey/attack/x-bullets-upper/executor/terminate/boss_fight.mcfunction
datapacks/omega-flowey/data/entity/function/player/room/enter.mcfunction
datapacks/omega-flowey/data/entity/function/player/room/exit.mcfunction
datapacks/omega-flowey/data/entity/function/player/room/spectator_box/enter.mcfunction
datapacks/omega-flowey/data/entity/function/player/room/spectator_box/exit.mcfunction
datapacks/omega-flowey/data/entity/function/player/room/underground/enter.mcfunction
datapacks/omega-flowey/data/entity/function/player/room/underground/exit.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/summit/room/cave/setup/text_displays.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/summit/room/outside/setup.mcfunction
datapacks/omega-flowey/data/omega-flowey/function/summit/room/pit/setup/text_displays.mcfunction
package-scripts/build.js
resourcepack/assets/omega-flowey/models/entity/decorative/summit-petal-pipe-right.ajblueprint
resourcepack/assets/omega-flowey/models/entity/decorative/summitpetalpipeleft.ajblueprint
resourcepack/assets/omega-flowey/models/entity/decorative/summitpetalpipetop.ajblueprint

This PR adds two more decorative models to support the outside tvscreen model on the Summit mountain.
---
---
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/f8a638136f394647bd9a851f80be64df1700fd20: ⚔️ decrease delay after xbullets attacks
- need to decrease this further, but will need to look into terminating earlier than the executor terminate
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/cf3c29c7ad6a26a08df9d870438ff281f3b1f278: ⚔️ decrease delay after friendliness-pellets
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit/613d6014a8def9e86418ae88c5fbb3336a70395b: 📍 move `Welcome...` text to be inline with `by TheAfroOfDoom` text
- https://github.com/TheAfroOfDoom/omega-flowey-minecraft-remastered/commit …

🍱 add left/top summit petal pipe decorative models

---

datapacks/omega-flowey/data/entity/function/utils/damage/as_player.mcfunction

We can temporarily disable the `showDeathMessages` gamerule when a player dies to a bossfight attack and display a custom message with `/tellraw`.

🔊 show custom death message when player dies during bossfight

---

datapacks/omega-flowey/data/entity/function/directorial/boss_fight/shared/arena_box/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/directorial/boss_fight/summit/initialize.mcfunction
datapacks/omega-flowey/data/entity/function/remove_animated_java_models/boss_fight.mcfunction
resourcepack/assets/omega-flowey/models/entity/hostile/omega-flowey/arena_box.ajblueprint

This PR adds a model that is summoned around the center of the arena that blocks out the spectator box from the inside-only. The spectator box can still view the arena with no issues, but the player in the arena will only see a black box when looking towards the spectator box.

🎥 hide spectator box from active bossfight player

---

datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/summit/phase/soul/initialize.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/summit/phase/soul/terminate.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/vanilla/phase/soul/initialize.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/vanilla/phase/soul/terminate.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/dentata-snakes/bullet/loop/after_bounce_as_bullet_head.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/executor/states/load_all_states/show_title.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/homing-vines-save-states/executor/states/save_all_states/show_title.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/x-bullets-upper-save-states/executor/states/load_all_states/show_title.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/x-bullets-upper-save-states/executor/states/save_all_states/show_title.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/soul/soul_0/executor/initialize/saved.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/soul/soul_5/executor/initialize.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/soul/soul_5/executor/initialize/saved.mcfunction

we never defined the `spectator` team. this was a long time coming.
easier to just use tags to track spectators anyway

♻️ replace `spectator` team references with `spectator_box` tag

---

datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/setup/text_displays.mcfunction

forgot to update this volume selector when we moved the interaction in -Z, so it wouldnt initialize and the link-click behavior was broken

🐛 fix GitHub link interaction entity not initializing

---

datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/dentata-snakes/bullet/loop.mcfunction

this was due to the fact that we now check `player.health` as an int score, and we were passing in a float damage amount. so the damage function failed
https://github.com/TheAfroOfDoom/omegaflowey-minecraft-remastered/blob/93339ab0a433ac1e66569dbfce90506a6cdb075f/datapacks/omegaflowey/data/omegaflowey.entity/function/utils/damage/as_player.mcfunction#L3-L4

🐛 fix `dentata-snakes` bullets not dealing damage

---

datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/active_player_display/as_text_display.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/setup/text_displays.mcfunction

it was off-center before. so we moved the player skull/health to center around the middle of the monitor instead of forcing the player skull to be in the center
| before | after |
|-|-|
| ![2024-10-12_15 28 49](https://github.com/user-attachments/assets/9a490504-2ba2-445c-83ae-0ab2b0b5f7d9) | ![2024-10-12_15 26 18](https://github.com/user-attachments/assets/e070308c-ab39-4f0a-a7e2-cf995bca7efd) |

💄 adjust "now playing" player head/health around center of monitor

---

package-scripts/build.js

we dont use these files in summit, so the summit RP/DPs don't need them

🔧 prune unused AJ exports from build

---

datapacks/omegaflowey/data/omegaflowey.admin/function/death_message/set_global.mcfunction
datapacks/omegaflowey/data/omegaflowey.admin/function/death_message/set_local.mcfunction
datapacks/omegaflowey/data/omegaflowey.admin/function/help.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/summit/initialize.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/remove_animated_java_models/summit.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/utils/damage.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/utils/damage/as_player/died.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/utils/damage/as_player/died/show_death_message.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/setup/const.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/setup/objectives.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/cave_back/setup.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/cave_back/setup/text_displays.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/setup/text_displays.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/setup/text_displays/join_queue/disable.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/cave/setup/text_displays/join_queue/enable.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/summit/room/outside/setup/text_displays.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/telemetry/admin/help.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/telemetry/admin/new_page/booth.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/telemetry/admin/new_page/bossfight.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/telemetry/admin/reset_triggers.mcfunction
datapacks/omegaflowey/data/omegaflowey.main/function/telemetry/admin/tick.mcfunction

committing this as a rebase and merge to keep the granular changes

🐛 various 2024/10/26 Summit internal playtest fixes and tuning

---

datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/vanilla/origin/at/x.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/directorial/boss_fight/vanilla/origin/setup.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/flies/bullet/initialize.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/flies/executor/initialize/indicator/presummon/flipped.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/flies/executor/initialize/indicator/presummon/normal.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/flies/indicator/loop/bullet/presummon.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/flies/indicator/loop/bullet/presummon/along_bottom.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/flies/indicator/loop/bullet/presummon/along_side.mcfunction
datapacks/omegaflowey/data/omegaflowey.entity/function/hostile/omega-flowey/attack/flies/indicator/loop/bullet/presummon/along_top.mcfunction
package-scripts.js

For Smithed Summit 2024, we skipped converting the `flies` attack to use relative coordinates + new arena bounds since it wasn't in the demo.
This PR updates the attack to use coordinates relative to the vanilla bossfight origin and shrinks its bounds to be like the rest of the attacks.
---
```mcfunction
function _:attack/flies
```

⚔️ convert flies summon coords to relative and shrink bounds

---

datapacks/omegaflowey/data/omegaflowey.entity/function/shared/run_as_active_player_or_spectator.mcfunction

- just temp disable the volume selector that was tuned for Summit

🐛 fix attack sounds not playing in vanilla map

---

.spyglassrc.json
datapacks/omegaflowey/data/_/function/active_player.mcfunction

- looking at the Spyglass logs locally, this decreased the `bind` phase from ~100s to ~1.5s.
- likely possible now due to various exclude improvements Spyglass has made since the last time this was configured
- now, test files are excluded properly and we won't get errors!

🔧 update spyglassrc `exclude` patterns

---

.vscode/extensions.json
resourcepack/assets/minecraft/shaders/core/rendertype_entity_cutout.fsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_cutout.vsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_cutout_no_cull.fsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_cutout_no_cull.vsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_cutout_no_cull_z_offset.fsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_cutout_no_cull_z_offset.vsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_no_outline.fsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_no_outline.vsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_solid.fsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_solid.vsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_translucent.fsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_translucent.vsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_translucent_cull.fsh
resourcepack/assets/minecraft/shaders/core/rendertype_entity_translucent_cull.vsh
resourcepack/assets/minecraft/shaders/core/rendertype_item_entity_translucent_cull.fsh
resourcepack/assets/minecraft/shaders/core/rendertype_item_entity_translucent_cull.vsh
resourcepack/assets/minecraft/shaders/include/emissive_utils.glsl

- added from a modified version of https://github.com/ShockMicro/VanillaDynamicEmissives
- version i have added here was whatever Smithed Summit 2024 used
- not sure what diffs (if any) there are with the above link but it's probably similar
- all this does is make it so certain pixel opacities render as emissive/emissive+transparent. used for super bright monitor screens, like the flowey TV
- extension https://marketplace.visualstudio.com/items?itemName=slevesque.shader for syntax highlighting of `.glsl`

➕ add shader resourcepack dependency
